import rsc
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'notepad.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1260, 961)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 1260, 961))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 145, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(244, 193, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(116, 68, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(155, 91, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 145, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 145, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(244, 195, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 145, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(244, 193, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(116, 68, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(155, 91, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 145, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 145, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(244, 195, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(116, 68, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 145, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(244, 193, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(116, 68, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(155, 91, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(116, 68, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(116, 68, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 145, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 145, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 136, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.stackedWidget.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Harlow Solid Italic")
        font.setPointSize(20)
        font.setItalic(True)
        self.stackedWidget.setFont(font)
        self.stackedWidget.setAutoFillBackground(False)
        self.stackedWidget.setStyleSheet("background-color: rgb(57, 145, 227);\n"
"background-image: url(:/newPrefix/writing-pad-3583553.jpg);")
        self.stackedWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.quit_button = QtWidgets.QPushButton(self.page)
        self.quit_button.setGeometry(QtCore.QRect(770, 570, 241, 121))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 228, 88))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 244, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 117, 79))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 156, 106))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 228, 88))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 228, 88))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 244, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 228, 88))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 244, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 117, 79))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 156, 106))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 228, 88))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 228, 88))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 244, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 117, 79))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 228, 88))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 244, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 117, 79))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 156, 106))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 117, 79))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 117, 79))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 228, 88))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 228, 88))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 234, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.quit_button.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Edwardian Script ITC")
        font.setPointSize(24)
        self.quit_button.setFont(font)
        self.quit_button.setStyleSheet("background-color: rgb(255, 228, 88);")
        self.quit_button.setObjectName("quit_button")
        self.graphicsView_4 = QtWidgets.QGraphicsView(self.page)
        self.graphicsView_4.setGeometry(QtCore.QRect(0, 0, 1260, 960))
        self.graphicsView_4.setStyleSheet("background-image: url(:/newPrefix/writing-pad-3583553_1280.jpg);")
        self.graphicsView_4.setObjectName("graphicsView_4")
        self.login_button = QtWidgets.QPushButton(self.page)
        self.login_button.setGeometry(QtCore.QRect(220, 180, 271, 121))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 228, 88))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 129, 174))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 76, 136))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 11, 49))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 15, 66))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 228, 88))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 228, 88))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 139, 177))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 228, 88))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 129, 174))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 76, 136))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 11, 49))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 15, 66))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 228, 88))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 228, 88))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 139, 177))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 11, 49))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 228, 88))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 129, 174))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 76, 136))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 11, 49))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 15, 66))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 11, 49))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 11, 49))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 228, 88))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 228, 88))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 23, 99))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.login_button.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Edwardian Script ITC")
        font.setPointSize(24)
        font.setItalic(False)
        self.login_button.setFont(font)
        self.login_button.setStyleSheet("background-color: rgb(255, 228, 88);")
        self.login_button.setAutoDefault(True)
        self.login_button.setDefault(True)
        self.login_button.setFlat(False)
        self.login_button.setObjectName("login_button")
        self.signup_button = QtWidgets.QPushButton(self.page)
        self.signup_button.setGeometry(QtCore.QRect(220, 350, 271, 121))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 228, 88))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(163, 220, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 194, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(27, 84, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(36, 113, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 228, 88))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 228, 88))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(154, 212, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 228, 88))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(163, 220, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 194, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(27, 84, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(36, 113, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 228, 88))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 228, 88))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(154, 212, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(27, 84, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 228, 88))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(163, 220, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 194, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(27, 84, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(36, 113, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(27, 84, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(27, 84, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 228, 88))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 228, 88))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(54, 169, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.signup_button.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Edwardian Script ITC")
        font.setPointSize(24)
        self.signup_button.setFont(font)
        self.signup_button.setStyleSheet("background-color: rgb(255, 228, 88);")
        self.signup_button.setObjectName("signup_button")
        self.graphicsView_4.raise_()
        self.quit_button.raise_()
        self.login_button.raise_()
        self.signup_button.raise_()
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.username_label = QtWidgets.QLabel(self.page_2)
        self.username_label.setGeometry(QtCore.QRect(180, 229, 251, 61))
        font = QtGui.QFont()
        font.setFamily("Edwardian Script ITC")
        font.setPointSize(20)
        self.username_label.setFont(font)
        self.username_label.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.username_label.setScaledContents(False)
        self.username_label.setAlignment(QtCore.Qt.AlignCenter)
        self.username_label.setObjectName("username_label")
        self.password_label = QtWidgets.QLabel(self.page_2)
        self.password_label.setGeometry(QtCore.QRect(180, 474, 251, 71))
        font = QtGui.QFont()
        font.setFamily("Edwardian Script ITC")
        font.setPointSize(20)
        self.password_label.setFont(font)
        self.password_label.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.password_label.setAlignment(QtCore.Qt.AlignCenter)
        self.password_label.setObjectName("password_label")
        self.username_text = QtWidgets.QTextEdit(self.page_2)
        self.username_text.setGeometry(QtCore.QRect(180, 295, 251, 61))
        self.username_text.setMaximumSize(QtCore.QSize(16777215, 125))
        font = QtGui.QFont()
        font.setFamily("Edwardian Script ITC")
        font.setPointSize(16)
        self.username_text.setFont(font)
        self.username_text.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.username_text.setObjectName("username_text")
        self.sign_in_button = QtWidgets.QPushButton(self.page_2)
        self.sign_in_button.setGeometry(QtCore.QRect(780, 600, 231, 91))
        font = QtGui.QFont()
        font.setFamily("Edwardian Script ITC")
        font.setPointSize(20)
        self.sign_in_button.setFont(font)
        self.sign_in_button.setStyleSheet("background-color: rgb(255, 170, 127);")
        self.sign_in_button.setObjectName("sign_in_button")
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.page_2)
        self.graphicsView_2.setGeometry(QtCore.QRect(0, 0, 1260, 961))
        self.graphicsView_2.setStyleSheet("background-image: url(:/newPrefix/writing-pad-3583553_1280.jpg);")
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.back_login_page = QtWidgets.QPushButton(self.page_2)
        self.back_login_page.setGeometry(QtCore.QRect(10, 20, 191, 71))
        font = QtGui.QFont()
        font.setFamily("Edwardian Script ITC")
        font.setPointSize(20)
        self.back_login_page.setFont(font)
        self.back_login_page.setStyleSheet("background-color: rgb(255, 170, 127);")
        self.back_login_page.setObjectName("back_login_page")
        self.password_text = QtWidgets.QLineEdit(self.page_2)
        self.password_text.setGeometry(QtCore.QRect(182, 560, 251, 61))
        self.password_text.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"border-color: rgb(0, 0, 0, 0);")
        self.password_text.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_text.setObjectName("password_text")
        self.graphicsView_2.raise_()
        self.username_label.raise_()
        self.password_label.raise_()
        self.username_text.raise_()
        self.sign_in_button.raise_()
        self.back_login_page.raise_()
        self.password_text.raise_()
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.register_button = QtWidgets.QPushButton(self.page_3)
        self.register_button.setGeometry(QtCore.QRect(670, 730, 261, 101))
        font = QtGui.QFont()
        font.setFamily("Edwardian Script ITC")
        font.setPointSize(16)
        self.register_button.setFont(font)
        self.register_button.setStyleSheet("background-color: rgb(255, 170, 127);")
        self.register_button.setObjectName("register_button")
        self.email_text_register = QtWidgets.QTextEdit(self.page_3)
        self.email_text_register.setGeometry(QtCore.QRect(760, 390, 256, 59))
        self.email_text_register.setMaximumSize(QtCore.QSize(16777215, 125))
        self.email_text_register.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.email_text_register.setObjectName("email_text_register")
        self.password_label_register = QtWidgets.QLabel(self.page_3)
        self.password_label_register.setGeometry(QtCore.QRect(330, 610, 271, 61))
        font = QtGui.QFont()
        font.setFamily("Edwardian Script ITC")
        font.setPointSize(12)
        self.password_label_register.setFont(font)
        self.password_label_register.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.password_label_register.setAlignment(QtCore.Qt.AlignCenter)
        self.password_label_register.setObjectName("password_label_register")
        self.email_label_register = QtWidgets.QLabel(self.page_3)
        self.email_label_register.setGeometry(QtCore.QRect(330, 390, 271, 61))
        font = QtGui.QFont()
        font.setFamily("Edwardian Script ITC")
        font.setPointSize(12)
        self.email_label_register.setFont(font)
        self.email_label_register.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.email_label_register.setScaledContents(False)
        self.email_label_register.setAlignment(QtCore.Qt.AlignCenter)
        self.email_label_register.setObjectName("email_label_register")
        self.name_label_register = QtWidgets.QLabel(self.page_3)
        self.name_label_register.setGeometry(QtCore.QRect(330, 170, 271, 61))
        font = QtGui.QFont()
        font.setFamily("Edwardian Script ITC")
        font.setPointSize(12)
        self.name_label_register.setFont(font)
        self.name_label_register.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.name_label_register.setScaledContents(True)
        self.name_label_register.setAlignment(QtCore.Qt.AlignCenter)
        self.name_label_register.setObjectName("name_label_register")
        self.name_text_register = QtWidgets.QTextEdit(self.page_3)
        self.name_text_register.setGeometry(QtCore.QRect(760, 170, 256, 59))
        self.name_text_register.setMaximumSize(QtCore.QSize(16777215, 125))
        self.name_text_register.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.name_text_register.setObjectName("name_text_register")
        self.lastname_label_register = QtWidgets.QLabel(self.page_3)
        self.lastname_label_register.setGeometry(QtCore.QRect(330, 280, 271, 61))
        font = QtGui.QFont()
        font.setFamily("Edwardian Script ITC")
        font.setPointSize(12)
        self.lastname_label_register.setFont(font)
        self.lastname_label_register.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.lastname_label_register.setScaledContents(False)
        self.lastname_label_register.setAlignment(QtCore.Qt.AlignCenter)
        self.lastname_label_register.setObjectName("lastname_label_register")
        self.lastname_text_register = QtWidgets.QTextEdit(self.page_3)
        self.lastname_text_register.setGeometry(QtCore.QRect(760, 280, 256, 59))
        self.lastname_text_register.setMaximumSize(QtCore.QSize(16777215, 125))
        self.lastname_text_register.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.lastname_text_register.setObjectName("lastname_text_register")
        self.username_label_register = QtWidgets.QLabel(self.page_3)
        self.username_label_register.setGeometry(QtCore.QRect(330, 500, 271, 61))
        font = QtGui.QFont()
        font.setFamily("Edwardian Script ITC")
        font.setPointSize(14)
        self.username_label_register.setFont(font)
        self.username_label_register.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.username_label_register.setScaledContents(False)
        self.username_label_register.setAlignment(QtCore.Qt.AlignCenter)
        self.username_label_register.setObjectName("username_label_register")
        self.username_text_register = QtWidgets.QTextEdit(self.page_3)
        self.username_text_register.setGeometry(QtCore.QRect(760, 500, 256, 62))
        self.username_text_register.setMaximumSize(QtCore.QSize(16777215, 125))
        self.username_text_register.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.username_text_register.setObjectName("username_text_register")
        self.graphicsView_3 = QtWidgets.QGraphicsView(self.page_3)
        self.graphicsView_3.setGeometry(QtCore.QRect(0, 0, 2000, 1000))
        self.graphicsView_3.setStyleSheet("background-image: url(:/newPrefix/writing-pad-3583553_1280.jpg);")
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.back_register_page = QtWidgets.QPushButton(self.page_3)
        self.back_register_page.setGeometry(QtCore.QRect(20, 30, 191, 61))
        font = QtGui.QFont()
        font.setFamily("Edwardian Script ITC")
        font.setPointSize(20)
        self.back_register_page.setFont(font)
        self.back_register_page.setStyleSheet("background-color: rgb(255, 170, 127);")
        self.back_register_page.setObjectName("back_register_page")
        self.password_text_register = QtWidgets.QLineEdit(self.page_3)
        self.password_text_register.setGeometry(QtCore.QRect(760, 610, 251, 61))
        self.password_text_register.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"border-color: rgb(0, 0, 0, 0);")
        self.password_text_register.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_text_register.setObjectName("password_text_register")
        self.graphicsView_3.raise_()
        self.register_button.raise_()
        self.email_text_register.raise_()
        self.password_label_register.raise_()
        self.email_label_register.raise_()
        self.name_label_register.raise_()
        self.name_text_register.raise_()
        self.lastname_label_register.raise_()
        self.lastname_text_register.raise_()
        self.username_label_register.raise_()
        self.username_text_register.raise_()
        self.back_register_page.raise_()
        self.password_text_register.raise_()
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.graphicsView_5 = QtWidgets.QGraphicsView(self.page_4)
        self.graphicsView_5.setGeometry(QtCore.QRect(0, 0, 2071, 1000))
        self.graphicsView_5.setStyleSheet("background-image: url(:/newPrefix/writing-pad-3583553_1280.jpg);")
        self.graphicsView_5.setObjectName("graphicsView_5")
        self.new_deck_name_textEdit = QtWidgets.QTextEdit(self.page_4)
        self.new_deck_name_textEdit.setGeometry(QtCore.QRect(710, 540, 391, 71))
        font = QtGui.QFont()
        font.setFamily("Edwardian Script ITC")
        font.setPointSize(14)
        self.new_deck_name_textEdit.setFont(font)
        self.new_deck_name_textEdit.setStyleSheet("background-color: rgb(255, 239, 110);")
        self.new_deck_name_textEdit.setObjectName("new_deck_name_textEdit")
        self.new_deck_name_label = QtWidgets.QLabel(self.page_4)
        self.new_deck_name_label.setGeometry(QtCore.QRect(600, 380, 591, 161))
        font = QtGui.QFont()
        font.setFamily("Edwardian Script ITC")
        font.setPointSize(22)
        self.new_deck_name_label.setFont(font)
        self.new_deck_name_label.setStyleSheet("background-color: rgb(0, 0, 0, 0);")
        self.new_deck_name_label.setAlignment(QtCore.Qt.AlignCenter)
        self.new_deck_name_label.setObjectName("new_deck_name_label")
        self.create_deck_done_button = QtWidgets.QPushButton(self.page_4)
        self.create_deck_done_button.setGeometry(QtCore.QRect(630, 600, 541, 171))
        font = QtGui.QFont()
        font.setFamily("Edwardian Script ITC")
        font.setPointSize(22)
        self.create_deck_done_button.setFont(font)
        self.create_deck_done_button.setStyleSheet("background-color: rgb(0, 0, 0, 0);")
        self.create_deck_done_button.setObjectName("create_deck_done_button")
        self.view_uncategorized_notes_button = QtWidgets.QPushButton(self.page_4)
        self.view_uncategorized_notes_button.setGeometry(QtCore.QRect(90, 450, 451, 101))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.view_uncategorized_notes_button.sizePolicy().hasHeightForWidth())
        self.view_uncategorized_notes_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Edwardian Script ITC")
        font.setPointSize(20)
        self.view_uncategorized_notes_button.setFont(font)
        self.view_uncategorized_notes_button.setStyleSheet("background-color: rgb(212, 226, 49);")
        self.view_uncategorized_notes_button.setObjectName("view_uncategorized_notes_button")
        self.logout_button = QtWidgets.QPushButton(self.page_4)
        self.logout_button.setGeometry(QtCore.QRect(190, 610, 241, 71))
        font = QtGui.QFont()
        font.setFamily("Edwardian Script ITC")
        font.setPointSize(20)
        self.logout_button.setFont(font)
        self.logout_button.setStyleSheet("background-color: rgb(212, 226, 49);")
        self.logout_button.setObjectName("logout_button")
        self.instant_note_create_button = QtWidgets.QPushButton(self.page_4)
        self.instant_note_create_button.setGeometry(QtCore.QRect(90, 90, 451, 101))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.instant_note_create_button.sizePolicy().hasHeightForWidth())
        self.instant_note_create_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Edwardian Script ITC")
        font.setPointSize(20)
        self.instant_note_create_button.setFont(font)
        self.instant_note_create_button.setStyleSheet("background-color: rgb(212, 226, 49);")
        self.instant_note_create_button.setObjectName("instant_note_create_button")
        self.new_deck_create_button = QtWidgets.QPushButton(self.page_4)
        self.new_deck_create_button.setGeometry(QtCore.QRect(91, 212, 451, 101))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.new_deck_create_button.sizePolicy().hasHeightForWidth())
        self.new_deck_create_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Edwardian Script ITC")
        font.setPointSize(20)
        self.new_deck_create_button.setFont(font)
        self.new_deck_create_button.setStyleSheet("background-color: rgb(212, 226, 49);")
        self.new_deck_create_button.setObjectName("new_deck_create_button")
        self.view_deck_button = QtWidgets.QPushButton(self.page_4)
        self.view_deck_button.setGeometry(QtCore.QRect(90, 330, 451, 101))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.view_deck_button.sizePolicy().hasHeightForWidth())
        self.view_deck_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Edwardian Script ITC")
        font.setPointSize(20)
        self.view_deck_button.setFont(font)
        self.view_deck_button.setStyleSheet("background-color: rgb(212, 226, 49);")
        self.view_deck_button.setObjectName("view_deck_button")
        self.graphicsView_5.raise_()
        self.new_deck_name_textEdit.raise_()
        self.create_deck_done_button.raise_()
        self.instant_note_create_button.raise_()
        self.new_deck_create_button.raise_()
        self.view_deck_button.raise_()
        self.new_deck_name_label.raise_()
        self.view_uncategorized_notes_button.raise_()
        self.logout_button.raise_()
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.label_3 = QtWidgets.QLabel(self.page_5)
        self.label_3.setGeometry(QtCore.QRect(630, 150, 301, 61))
        font = QtGui.QFont()
        font.setFamily("Edwardian Script ITC")
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgb(0, 0, 0,0);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.note_name_text_edit = QtWidgets.QTextEdit(self.page_5)
        self.note_name_text_edit.setGeometry(QtCore.QRect(950, 150, 201, 64))
        font = QtGui.QFont()
        font.setFamily("Edwardian Script ITC")
        font.setPointSize(12)
        self.note_name_text_edit.setFont(font)
        self.note_name_text_edit.setStyleSheet("background-color: rgb(255, 240, 199);")
        self.note_name_text_edit.setObjectName("note_name_text_edit")
        self.graphicsView_6 = QtWidgets.QGraphicsView(self.page_5)
        self.graphicsView_6.setGeometry(QtCore.QRect(0, 0, 2000, 1000))
        self.graphicsView_6.setStyleSheet("background-image: url(:/newPrefix/writing-pad-3583553_1280.jpg);")
        self.graphicsView_6.setObjectName("graphicsView_6")
        self.reminder_dateTime_edit = QtWidgets.QDateTimeEdit(self.page_5)
        self.reminder_dateTime_edit.setGeometry(QtCore.QRect(20, 470, 601, 81))
        font = QtGui.QFont()
        font.setFamily("Edwardian Script ITC")
        font.setPointSize(14)
        self.reminder_dateTime_edit.setFont(font)
        self.reminder_dateTime_edit.setStyleSheet("background-color: rgb(255, 162, 146);")
        self.reminder_dateTime_edit.setObjectName("reminder_dateTime_edit")
        self.dateTime_edit_done_button = QtWidgets.QPushButton(self.page_5)
        self.dateTime_edit_done_button.setGeometry(QtCore.QRect(310, 580, 171, 61))
        font = QtGui.QFont()
        font.setFamily("Edwardian Script ITC")
        font.setPointSize(18)
        self.dateTime_edit_done_button.setFont(font)
        self.dateTime_edit_done_button.setStyleSheet("background-color: rgb(255, 162, 146);")
        self.dateTime_edit_done_button.setObjectName("dateTime_edit_done_button")
        self.back_newnote_page = QtWidgets.QPushButton(self.page_5)
        self.back_newnote_page.setGeometry(QtCore.QRect(20, 20, 191, 71))
        font = QtGui.QFont()
        font.setFamily("Edwardian Script ITC")
        font.setPointSize(20)
        self.back_newnote_page.setFont(font)
        self.back_newnote_page.setStyleSheet("background-color: rgb(255, 170, 127);")
        self.back_newnote_page.setObjectName("back_newnote_page")
        self.page_newnote_note_textedit = QtWidgets.QPlainTextEdit(self.page_5)
        self.page_newnote_note_textedit.setGeometry(QtCore.QRect(670, 220, 471, 591))
        font = QtGui.QFont()
        font.setFamily("Edwardian Script ITC")
        font.setPointSize(18)
        self.page_newnote_note_textedit.setFont(font)
        self.page_newnote_note_textedit.setStyleSheet("background-color: rgb(0, 0, 0, 0);\n"
"border-color: rgb(0, 0, 0, 0);")
        self.page_newnote_note_textedit.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.page_newnote_note_textedit.setObjectName("page_newnote_note_textedit")
        self.page_newnote_save_button = QtWidgets.QPushButton(self.page_5)
        self.page_newnote_save_button.setGeometry(QtCore.QRect(190, 170, 231, 91))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page_newnote_save_button.sizePolicy().hasHeightForWidth())
        self.page_newnote_save_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Edwardian Script ITC")
        font.setPointSize(14)
        self.page_newnote_save_button.setFont(font)
        self.page_newnote_save_button.setStyleSheet("background-color: rgb(212, 226, 49);")
        self.page_newnote_save_button.setObjectName("page_newnote_save_button")
        self.page_newnote_reminder_button = QtWidgets.QPushButton(self.page_5)
        self.page_newnote_reminder_button.setGeometry(QtCore.QRect(190, 270, 231, 101))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page_newnote_reminder_button.sizePolicy().hasHeightForWidth())
        self.page_newnote_reminder_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Edwardian Script ITC")
        font.setPointSize(14)
        self.page_newnote_reminder_button.setFont(font)
        self.page_newnote_reminder_button.setStyleSheet("background-color: rgb(212, 226, 49);")
        self.page_newnote_reminder_button.setObjectName("page_newnote_reminder_button")
        self.graphicsView_6.raise_()
        self.label_3.raise_()
        self.note_name_text_edit.raise_()
        self.reminder_dateTime_edit.raise_()
        self.dateTime_edit_done_button.raise_()
        self.page_newnote_save_button.raise_()
        self.page_newnote_reminder_button.raise_()
        self.back_newnote_page.raise_()
        self.page_newnote_note_textedit.raise_()
        self.stackedWidget.addWidget(self.page_5)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.label = QtWidgets.QLabel(self.page_7)
        self.label.setGeometry(QtCore.QRect(10, 340, 611, 201))
        font = QtGui.QFont()
        font.setFamily("Edwardian Script ITC")
        font.setPointSize(36)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(0, 0,0, 0);")
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.graphicsView = QtWidgets.QGraphicsView(self.page_7)
        self.graphicsView.setGeometry(QtCore.QRect(0, 0, 1280, 1000))
        self.graphicsView.setStyleSheet("background-image: url(:/newPrefix/writing-pad-3583553_1280.jpg);")
        self.graphicsView.setObjectName("graphicsView")
        self.back_deck_page = QtWidgets.QPushButton(self.page_7)
        self.back_deck_page.setGeometry(QtCore.QRect(20, 20, 191, 61))
        font = QtGui.QFont()
        font.setFamily("Edwardian Script ITC")
        font.setPointSize(20)
        self.back_deck_page.setFont(font)
        self.back_deck_page.setStyleSheet("background-color: rgb(255, 170, 127);")
        self.back_deck_page.setObjectName("back_deck_page")
        self.scrollArea = QtWidgets.QScrollArea(self.page_7)
        self.scrollArea.setGeometry(QtCore.QRect(670, 169, 451, 631))
        self.scrollArea.setStyleSheet("background-color: rgb(0, 0,0, 0);")
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 451, 631))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.graphicsView.raise_()
        self.label.raise_()
        self.back_deck_page.raise_()
        self.scrollArea.raise_()
        self.stackedWidget.addWidget(self.page_7)
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setObjectName("page_8")
        self.page_newnote_delete_button_5 = QtWidgets.QPushButton(self.page_8)
        self.page_newnote_delete_button_5.setGeometry(QtCore.QRect(290, 640, 221, 60))
        self.page_newnote_delete_button_5.setStyleSheet("background-color: rgb(212, 226, 49);")
        self.page_newnote_delete_button_5.setObjectName("page_newnote_delete_button_5")
        self.stackedWidget.addWidget(self.page_8)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.page_newnote_save_button_2 = QtWidgets.QPushButton(self.page_6)
        self.page_newnote_save_button_2.setGeometry(QtCore.QRect(1310, 820, 291, 111))
        font = QtGui.QFont()
        font.setFamily("Edwardian Script ITC")
        font.setPointSize(20)
        self.page_newnote_save_button_2.setFont(font)
        self.page_newnote_save_button_2.setStyleSheet("background-color: rgb(212, 226, 49);")
        self.page_newnote_save_button_2.setObjectName("page_newnote_save_button_2")
        self.page_newnote_delete_button_2 = QtWidgets.QPushButton(self.page_6)
        self.page_newnote_delete_button_2.setGeometry(QtCore.QRect(210, 600, 221, 81))
        font = QtGui.QFont()
        font.setFamily("Edwardian Script ITC")
        font.setPointSize(16)
        self.page_newnote_delete_button_2.setFont(font)
        self.page_newnote_delete_button_2.setStyleSheet("background-color: rgb(255, 225, 135);")
        self.page_newnote_delete_button_2.setObjectName("page_newnote_delete_button_2")
        self.graphicsView_7 = QtWidgets.QGraphicsView(self.page_6)
        self.graphicsView_7.setGeometry(QtCore.QRect(0, 0, 1260, 961))
        self.graphicsView_7.setStyleSheet("background-image: url(:/newPrefix/writing-pad-3583553_1280.jpg);")
        self.graphicsView_7.setObjectName("graphicsView_7")
        self.back_show_note_page = QtWidgets.QPushButton(self.page_6)
        self.back_show_note_page.setGeometry(QtCore.QRect(20, 20, 181, 61))
        font = QtGui.QFont()
        font.setFamily("Edwardian Script ITC")
        font.setPointSize(20)
        self.back_show_note_page.setFont(font)
        self.back_show_note_page.setStyleSheet("background-color: rgb(255, 170, 127);")
        self.back_show_note_page.setObjectName("back_show_note_page")
        self.page_newnote_newnote_button = QtWidgets.QPushButton(self.page_6)
        self.page_newnote_newnote_button.setGeometry(QtCore.QRect(210, 470, 221, 81))
        font = QtGui.QFont()
        font.setFamily("Edwardian Script ITC")
        font.setPointSize(16)
        self.page_newnote_newnote_button.setFont(font)
        self.page_newnote_newnote_button.setStyleSheet("background-color: rgb(255, 225, 135);")
        self.page_newnote_newnote_button.setObjectName("page_newnote_newnote_button")
        self.page_newnote_shownote_textedit = QtWidgets.QPlainTextEdit(self.page_6)
        self.page_newnote_shownote_textedit.setGeometry(QtCore.QRect(670, 150, 471, 591))
        font = QtGui.QFont()
        font.setFamily("Edwardian Script ITC")
        font.setPointSize(18)
        self.page_newnote_shownote_textedit.setFont(font)
        self.page_newnote_shownote_textedit.setStyleSheet("background-color: rgb(0, 0, 0, 0);\n"
"border-color: rgb(0, 0, 0, 0);")
        self.page_newnote_shownote_textedit.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.page_newnote_shownote_textedit.setObjectName("page_newnote_shownote_textedit")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.page_6)
        self.scrollArea_2.setGeometry(QtCore.QRect(670, 170, 451, 631))
        self.scrollArea_2.setStyleSheet("background-color: rgb(0, 0,0, 0);")
        self.scrollArea_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 451, 631))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.label_2 = QtWidgets.QLabel(self.page_6)
        self.label_2.setGeometry(QtCore.QRect(10, 120, 611, 201))
        font = QtGui.QFont()
        font.setFamily("Edwardian Script ITC")
        font.setPointSize(36)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(0, 0,0, 0);")
        self.label_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.page_newnote_edit_button = QtWidgets.QPushButton(self.page_6)
        self.page_newnote_edit_button.setGeometry(QtCore.QRect(210, 470, 221, 81))
        font = QtGui.QFont()
        font.setFamily("Edwardian Script ITC")
        font.setPointSize(16)
        self.page_newnote_edit_button.setFont(font)
        self.page_newnote_edit_button.setStyleSheet("background-color: rgb(255, 225, 135);")
        self.page_newnote_edit_button.setObjectName("page_newnote_edit_button")
        self.page_newnote_update_button = QtWidgets.QPushButton(self.page_6)
        self.page_newnote_update_button.setGeometry(QtCore.QRect(210, 600, 221, 81))
        font = QtGui.QFont()
        font.setFamily("Edwardian Script ITC")
        font.setPointSize(16)
        self.page_newnote_update_button.setFont(font)
        self.page_newnote_update_button.setStyleSheet("background-color: rgb(255, 225, 135);")
        self.page_newnote_update_button.setObjectName("page_newnote_update_button")
        self.graphicsView_7.raise_()
        self.page_newnote_save_button_2.raise_()
        self.page_newnote_delete_button_2.raise_()
        self.back_show_note_page.raise_()
        self.page_newnote_newnote_button.raise_()
        self.page_newnote_shownote_textedit.raise_()
        self.scrollArea_2.raise_()
        self.label_2.raise_()
        self.page_newnote_edit_button.raise_()
        self.page_newnote_update_button.raise_()
        self.stackedWidget.addWidget(self.page_6)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.signup_button, self.quit_button)
        MainWindow.setTabOrder(self.quit_button, self.username_text)
        MainWindow.setTabOrder(self.username_text, self.login_button)
        MainWindow.setTabOrder(self.login_button, self.sign_in_button)
        MainWindow.setTabOrder(self.sign_in_button, self.register_button)
        MainWindow.setTabOrder(self.register_button, self.email_text_register)
        MainWindow.setTabOrder(self.email_text_register, self.name_text_register)
        MainWindow.setTabOrder(self.name_text_register, self.lastname_text_register)
        MainWindow.setTabOrder(self.lastname_text_register, self.username_text_register)
        MainWindow.setTabOrder(self.username_text_register, self.instant_note_create_button)
        MainWindow.setTabOrder(self.instant_note_create_button, self.new_deck_create_button)
        MainWindow.setTabOrder(self.new_deck_create_button, self.view_deck_button)
        MainWindow.setTabOrder(self.view_deck_button, self.reminder_dateTime_edit)
        MainWindow.setTabOrder(self.reminder_dateTime_edit, self.dateTime_edit_done_button)
        MainWindow.setTabOrder(self.dateTime_edit_done_button, self.page_newnote_save_button)
        MainWindow.setTabOrder(self.page_newnote_save_button, self.page_newnote_reminder_button)
        MainWindow.setTabOrder(self.page_newnote_reminder_button, self.page_newnote_delete_button_5)
        MainWindow.setTabOrder(self.page_newnote_delete_button_5, self.page_newnote_save_button_2)
        MainWindow.setTabOrder(self.page_newnote_save_button_2, self.page_newnote_delete_button_2)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.quit_button.setText(_translate("MainWindow", "Quit"))
        self.login_button.setText(_translate("MainWindow", "‍Login"))
        self.signup_button.setText(_translate("MainWindow", "Sign up"))
        self.username_label.setText(_translate("MainWindow", "Username"))
        self.password_label.setText(_translate("MainWindow", "password"))
        self.sign_in_button.setText(_translate("MainWindow", "Sign in"))
        self.back_login_page.setText(_translate("MainWindow", "Back"))
        self.register_button.setText(_translate("MainWindow", "Register"))
        self.password_label_register.setText(_translate("MainWindow", "password"))
        self.email_label_register.setText(_translate("MainWindow", "Email"))
        self.name_label_register.setText(_translate("MainWindow", "Name"))
        self.lastname_label_register.setText(_translate("MainWindow", "Last Name"))
        self.username_label_register.setText(_translate("MainWindow", "Username"))
        self.back_register_page.setText(_translate("MainWindow", "Back"))
        self.new_deck_name_label.setText(_translate("MainWindow", "Deck Name"))
        self.create_deck_done_button.setText(_translate("MainWindow", "Create Deck!"))
        self.view_uncategorized_notes_button.setText(_translate("MainWindow", "View Previous Notes"))
        self.logout_button.setText(_translate("MainWindow", "Logout"))
        self.instant_note_create_button.setText(_translate("MainWindow", "Instant Note"))
        self.new_deck_create_button.setText(_translate("MainWindow", "New Deck"))
        self.view_deck_button.setText(_translate("MainWindow", "View My Decks"))
        self.label_3.setText(_translate("MainWindow", "Note Name"))
        self.dateTime_edit_done_button.setText(_translate("MainWindow", "Done"))
        self.back_newnote_page.setText(_translate("MainWindow", "Back"))
        self.page_newnote_save_button.setText(_translate("MainWindow", "Save"))
        self.page_newnote_reminder_button.setText(_translate("MainWindow", "Set Reminder"))
        self.label.setText(_translate("MainWindow", "My Decks"))
        self.back_deck_page.setText(_translate("MainWindow", "Back"))
        self.page_newnote_delete_button_5.setText(_translate("MainWindow", "Quit"))
        self.page_newnote_save_button_2.setText(_translate("MainWindow", "New Note"))
        self.page_newnote_delete_button_2.setText(_translate("MainWindow", "Delete"))
        self.back_show_note_page.setText(_translate("MainWindow", "Back"))
        self.page_newnote_newnote_button.setText(_translate("MainWindow", "New Note"))
        self.label_2.setText(_translate("MainWindow", "Deck"))
        self.page_newnote_edit_button.setText(_translate("MainWindow", "Edit"))
        self.page_newnote_update_button.setText(_translate("MainWindow", "Update"))

